name: MacOS Build with Boost Fetch

on:
  push:
    branches: [ main, cmake ]
    paths:
      - ".github/workflows/macos_with_boost_fetch.yml"
      - "src/**"
      - "CMakeLists.txt"
  pull_request:
    branches: [ main ]
    paths:
      - ".github/workflows/macos_with_boost_fetch.yml"
      - "src/**"
      - "CMakeLists.txt"

jobs:
  build:
    runs-on: macos-latest
    env:
      CMAKE_PREFIX_PATH: ${{ github.workspace }}\.local
    steps:
    - uses: actions/checkout@v2

    - name: Install HWLoc
      run: brew install hwloc

    - name: Configure CMake
      run: cmake -S . -B build -DHPX_WITH_FETCH_BOOST=ON
        
    - name: Build
      run: cmake --build build --config Release --parallel

    - name: Execute
      run: ./build/opt_bench

