name: Windows Build with HWLoc Fetch

on:
  push:
    branches: [ main, cmake ]
    paths:
      - ".github/workflows/windows_with_hwloc_fetch.yml"
      - "src/**"
      - "CMakeLists.txt"
  pull_request:
    branches: [ main ]
    paths:
      - ".github/workflows/windows_with_hwloc_fetch.yml"
      - "src/**"
      - "CMakeLists.txt"

jobs:
  build:
    runs-on: windows-2022
    env:
      CMAKE_PREFIX_PATH: ${{ github.workspace }}\.local
    steps:
    - uses: actions/checkout@v2

    - name: Install Boost
      run: |
        vcpkg integrate install
        vcpkg install boost
        
    - name: Configure CMake
      run: cmake -S . -B build -DHPX_WITH_FETCH_HWLOC=On "-DCMAKE_TOOLCHAIN_FILE=$env:VCPKG_INSTALLATION_ROOT\scripts\buildsystems\vcpkg.cmake"
        
    - name: Build
      run: cmake --build build --config Release --parallel

    - name: Execute
      run: .\build\Release\opt_bench.exe

